#!/bin/bash
#PiMP MOTD Generator
#V1.0 by sling00
PIMP_VERSION=`sed -n '2,2p' /etc/version | cut -d "-" -f 1`
GETGFX_VENDOR=`sed -n '2,2p' /etc/version | cut -d "-" -f 2`
DRIVER_VERSION=`sed -n '2,2p' /etc/version | cut -d "-" -f 3`
CPUNAME=`cat /proc/cpuinfo | grep '^model name' | cut -d":" -f2 | head -1 | xargs`
CPUCORES=`cat /proc/cpuinfo | grep '^model name' | wc -l`
CPUMHZ=`cat /proc/cpuinfo | grep '^cpu MH' | cut -d":" -f2 | cut -d"." -f1| head -1| xargs`
MEMSIZE=`cat /proc/meminfo | grep 'MemTotal' | cut -d":" -f2 | xargs | cut -d" " -f1 | awk '{ rounded = sprintf("%1.0f", $1/1024/1024); print rounded }'`
if [ $GETGFX_VENDOR = "amd" ]; then
        GFX_VENDOR="ATI Catalyst: $DRIVER_VERSION"
    else 
        GFX_VENDOR="Nvidia Forceware: $DRIVER_VERSION"
fi

OUT=">> /tmp/motd.tail"
echo "       .__" $OUT
echo "______ |__| _____ ______  Portable Instant Mining Platform" $OUT
echo "\____ \|  |/     \\____ \     Pimp Version $PIMP_VERSION" $OUT
echo "|  |_> >  |  Y Y  \  |_> >  $GFX_VENDOR" $OUT
echo "|   __/|__|__|_|  /   __/   Support: #PiMP on FreenodeIRC" $OUT
echo "|__|            \/|__|           http://getPiMP.org" $OUT
echo "Type pimp for a list of pimp console shortcuts and commands" $OUT
echo "CPU: $CPUNAME" $OUT
echo "Cores: $CPUCORES @ $CPUMHZ Mhz Memory: $MEMSIZE GB" $OUT
cat /tmp/minerstats $OUT

 if [ -f /opt/ifmi/gpucountbad ]; then
        echo "=======================================================================" $OUT
        echo "WARNING: Detected GPU count is LESS than previous boot" $OUT
        echo "This message will not go away until you run:" $OUT
        echo "resetgpu" $OUT
        echo "=======================================================================" $OUT
fi
if [ -f /opt/pimp/gpudiff ]; then
        echo "The following GPU's are missing" $OUT
        cat /opt/pimp/gpudiff | while read line; do
        echo $line $OUT
        done
        echo "=======================================================================" $OUT
fi
