#!/bin/bash
#PiMP MOTD Generator
#V1.0 by sling00
PIMP_VERSION=`sed -n '2,2p' /etc/version | cut -d "-" -f 1`
GETGFX_VENDOR=`sed -n '2,2p' /etc/version | cut -d "-" -f 2`
DRIVER_VERSION=`sed -n '2,2p' /etc/version | cut -d "-" -f 3`
CPUNAME=`cat /proc/cpuinfo | grep '^model name' | cut -d":" -f2 | head -1 | xargs`
CPUCORES=`cat /proc/cpuinfo | grep '^model name' | wc -l`
CPUMHZ=`cat /proc/cpuinfo | grep '^cpu MH' | cut -d":" -f2 | cut -d"." -f1| head -1| xargs`
MEMSIZE=`cat /proc/meminfo | grep 'MemTotal' | cut -d":" -f2 | xargs | cut -d" " -f1 | awk '{ rounded = sprintf("%1.0f", $1/1024/1024); print rounded }'`
if [ $GETGFX_VENDOR = "amd" ]; then
        GFX_VENDOR="ATI Catalyst: $DRIVER_VERSION"
    else 
        GFX_VENDOR="Nvidia Forceware: $DRIVER_VERSION"
fi

echo "       .__" >> /tmp/motd.tail
echo "______ |__| _____ ______  Portable Instant Mining Platform" >> /tmp/motd.tail
echo "\____ \|  |/     \\____ \     Pimp Version $PIMP_VERSION" >> /tmp/motd.tail
echo "|  |_> >  |  Y Y  \  |_> >  $GFX_VENDOR" >> /tmp/motd.tail
echo "|   __/|__|__|_|  /   __/   Support: #PiMP on FreenodeIRC" >> /tmp/motd.tail
echo "|__|            \/|__|           http://getPiMP.org" >> /tmp/motd.tail
echo "Type pimp for a list of pimp console shortcuts and commands" >> /tmp/motd.tail
echo "CPU: $CPUNAME" >> /tmp/motd.tail
echo "Cores: $CPUCORES @ $CPUMHZ Mhz Memory: $MEMSIZE GB" >> /tmp/motd.tail
cat /tmp/minerstats >> /tmp/motd.tail

 if [ -f /opt/ifmi/gpucountbad ]; then
        echo "=======================================================================" >> /tmp/motd.tail
        echo "WARNING: Detected GPU count is LESS than previous boot" >> /tmp/motd.tail
        echo "This message will not go away until you run:" >> /tmp/motd.tail
        echo "resetgpu" >> /tmp/motd.tail
        echo "=======================================================================" >> /tmp/motd.tail
fi
if [ -f /opt/pimp/gpudiff ]; then
        echo "The following GPU's are missing" >> /tmp/motd.tail
        cat /opt/pimp/gpudiff | while read line; do
        echo $line >> /tmp/motd.tail
        done
        echo "=======================================================================" >> /tmp/motd.tail
fi
