#!/usr/bin/perl

use warnings;
use strict;
use File::Copy; 
use YAML qw( DumpFile );
# use Text::Tabs;
my $login = (getpwuid $>);
die "must run as root" if ($login ne 'root');
#die "no arguments" if ($ARGV[0] eq "");

 require '/opt/ifmi/pm-common.pl';

my $conf = &getConfig;
my %conf = %{$conf};
my $conffile = "/opt/ifmi/poolmanager.conf";
my $currentm = $conf{settings}{current_mconf};

if (!defined $ARGV[0] || $ARGV[0] eq "") {
  my $currmconf = ${$conf}{settings}{current_mconf}; 
  my $mconf = $conf{miners}{$currmconf}{savepath};
  &editConfig($mconf);
}
  my $swopt = $ARGV[0]; 
if (defined $ARGV[0] && $ARGV[0] eq "help" ) {
  print "\nActive Profile: " . $conf{miners}{$currentm}{mconfig} . "\n\n"; 
  print "Available Profles: \n";
  print "# - Name - \tConf file location:\n";
  print "========================================================\n";
  foreach my $mid (sort keys %{$conf{miners}}) {
        my $mname = $conf{miners}{$mid}{mconfig};
        my $mpath = $conf{miners}{$mid}{mpath};
        my $mopts = $conf{miners}{$mid}{mopts};
        my $mconf = $conf{miners}{$mid}{savepath};
        print "$mid - $mname -\t $mconf\n";
    #    my $shortconf = $conf [^/opt/ifmi]([^/]+)
        #print "$shortmconf\n"
     }
    print "========================================================\n";
    print "Usage: 'edit X' where X is a profile number.\n If no number is specified it will edit the currently active profile.\n";
} elsif (defined $swopt) {
   my $mconf2;
    if ($swopt ne $conf{settings}{current_mconf}) { 
      $mconf2 = $conf{miners}{$swopt}{savepath};
      &editConfig($mconf2);
    }
 } 
sub editConfig {
 my $mconf1 = $_[0];
 system ("/usr/bin/nano", $mconf1);
}
