#!/bin/bash
source /usr/share/initramfs-tools/hook-functions

PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac
	cp /usr/share/initramfs-tools/pci.ids ${DESTDIR}/pci.ids
	copy_exec /usr/bin/cut	/bin/cut
        copy_exec /bin/grep     /bin/grep
        copy_exec /usr/share/initramfs-tools/lspci /bin/lspci

